name = "PAndQ"
uuid = "0e9bd771-5675-474a-ac7f-e6301f653425"
authors = ["Jakob Peters <jakobj.peters@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[weakdeps]
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[extensions]
LatexifyExtension = "Latexify"
MarkdownExtension = "Markdown"

[compat]
AbstractTrees = "0.4"
PrettyTables = "2"
julia = "1"
